# Generated by Django 5.1.7 on 2026-03-18 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_options_and_more'),
        ('restaurant', '0005_remove_restaurantprofile_menu_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='assigned_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='restaurant.restauranttable'),
        ),
    ]
