# Generated by Django 5.1.7 on 2026-03-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeddate',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='blockedtimeslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='businesshour',
            options={'ordering': ['weekday', 'opens_at']},
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='menu_pdf',
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
