# Generated by Django 5.1.7 on 2026-03-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_blockeddate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_assets/'),
        ),
    ]
