# Generated by Django 5.1.7 on 2026-03-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='menu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_subtitle',
            field=models.CharField(default='Una experiencia gastronómica en La Fortuna.', max_length=220),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_title',
            field=models.CharField(default='Reserva en Travesía', max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
