# Generated by Django 5.1.7 on 2026-03-18 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantprofile_menu_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='menu_pdf',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='regular_capacity_per_slot',
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_title',
            field=models.CharField(default='Reserva tu mesa en Travesía', max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurantprofile')),
            ],
            options={
                'ordering': ['capacity', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
    ]
