# Generated by Django 5.1.7 on 2026-03-21 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurantprofile_menu_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='reservation_duration_minutes',
            field=models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)]),
        ),
    ]
